name: Perform Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  collection-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.ls.outputs.packages }}
    steps:
      - uses: actions/checkout@v2
      - name: Gather package directories
        id: ls
        run: echo "packages=[$(ls -d packages/* | sed 's/[^[:alnum:]]/\\&/g' | sed 's/.*/"&",/' | tr -d '\n' | sed '$s/,$//')]" >> $GITHUB_OUTPUT

  Test-PR:
    runs-on: ubuntu-latest
    needs: collection-packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.collection-packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pogfi/pnpm-install-cache@v0.0.2
        name: Install pnpm

      - name: Test
        run: pnpm run -C ${{ matrix.package }} test --run --reporter=verbose

      - name: Build Package
        run: pnpm run -C ${{ matrix.package }} -r build

      - name: Clean cache
        run: pnpm store prune
